Web Crawling

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import bs4 as bs4
import requests 
import sklearn as skhynik
import adodbapi as ad
import pygame as pg
import asttokens
import

pygame 2.6.1 (SDL 2.28.4, Python 3.11.9)
Hello from the pygame community. https://www.pygame.org/contribute.html

In [20]:
import pandas as pd
from pymongo import MongoClient


uri = "mongodb://mrin9379_db_user:iOxgQWXsj7i30kSF@ac-8dydvgo-shard-00-00.b8wslzx.mongodb.net:27017,ac-8dydvgo-shard-00-01.b8wslzx.mongodb.net:27017,ac-8dydvgo-shard-00-02.b8wslzx.mongodb.net:27017/?ssl=true&replicaSet=atlas-fb5v22-shard-0&authSource=admin&appName=Cluster0"
client = MongoClient(uri)


db = client['Fahasa'] 
collection = db['Fahasa_Trending']


print("Đang tải dữ liệu...")
cursor = collection.find({}) 


df = pd.DataFrame(list(cursor))


if '_id' in df.columns:
    df.drop(columns=['_id'], inplace=True)


print("Tải dữ liệu thành công!")
display(df.head())

Đang tải dữ liệu...
Tải dữ liệu thành công!

,ProductName,Price,QuantitySold,Category,Author,Publisher,Supplier,CoverType,Pages,ProductURL
0,Xứ Sở Miên Man - Phiên Bản Book Charm - Bìa Cứng,415000.0,1000,SÁCH TIẾNG VIỆT > VĂN HỌC > TIỂU THUYẾT,Jun Phạm,Phụ Nữ Việt Nam,Skybooks,Bìa Cứng,456.0,https://www.fahasa.com/xu-so-mien-man-phien-ba...
1,Boxset Bộ Sách Dấu Ấn 10 Năm Omega+ (Hộp 10 Cu...,4000000.0,48,SÁCH TIẾNG VIỆT > LỊCH SỬ - ĐỊA LÝ - TÔN... > ...,Nhiều Tác Giả,"Thế Giới, Tri Thức, Văn Học, Dân Trí",CÔNG TY CỔ PHẦN SÁCH OMEGA VIỆT NAM,Bộ Hộp,5280.0,https://www.fahasa.com/boxset-bo-sach-dau-an-1...
2,Shikimori Đâu Chỉ Dễ Thương - Tập 1 - Tặng Kèm...,33250.0,610,SÁCH TIẾNG VIỆT > MANGA - COMIC > MANGA > MANG...,Keigo Maki,Kim Đồng,Nhà Xuất Bản Kim Đồng,Bìa Mềm,144.0,https://www.fahasa.com/shikimori-dau-chi-de-th...
3,Boxset Sherlock Holmes Toàn Tập (Hộp 3 Tập) - ...,1090000.0,60,SÁCH TIẾNG VIỆT > VĂN HỌC > TRUYỆN TRINH THÁM ...,Sir Arthur Conan Doyle,Văn Học,Đông A,Bộ Hộp,1808.0,https://www.fahasa.com/boxset-sherlock-holmes-...
4,Combo Sách Giáo Trình New HSK 1 + Sổ Tay Học V...,325800.0,3000,SÁCH TIẾNG VIỆT > SÁCH HỌC NGOẠI NGỮ > TIẾNG HOA,Nhiều Tác Giả,Dân Trí,ZenBooks,Bìa Mềm,288.0,https://www.fahasa.com/combo-sach-giao-trinh-n...

### Đọc dữ liệu

In [21]:
df_origin = df.copy()            
print(df.shape)            
df.info()
df.head()

(923, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductName   923 non-null    object
 1   Price         898 non-null    float64
 2   QuantitySold  923 non-null    int64
 3   Category      923 non-null    object
 4   Author        923 non-null    object
 5   Publisher     923 non-null    object
 6   Supplier      923 non-null    object
 7   CoverType     923 non-null    object
 8   Pages         848 non-null    float64
 9   ProductURL    923 non-null    object
dtypes: float64(2), int64(1), object(7)
memory usage: 72.2+ KB

,ProductName,Price,QuantitySold,Category,Author,Publisher,Supplier,CoverType,Pages,ProductURL
0,Xứ Sở Miên Man - Phiên Bản Book Charm - Bìa Cứng,415000.0,1000,SÁCH TIẾNG VIỆT > VĂN HỌC > TIỂU THUYẾT,Jun Phạm,Phụ Nữ Việt Nam,Skybooks,Bìa Cứng,456.0,https://www.fahasa.com/xu-so-mien-man-phien-ba...
1,Boxset Bộ Sách Dấu Ấn 10 Năm Omega+ (Hộp 10 Cu...,4000000.0,48,SÁCH TIẾNG VIỆT > LỊCH SỬ - ĐỊA LÝ - TÔN... > ...,Nhiều Tác Giả,"Thế Giới, Tri Thức, Văn Học, Dân Trí",CÔNG TY CỔ PHẦN SÁCH OMEGA VIỆT NAM,Bộ Hộp,5280.0,https://www.fahasa.com/boxset-bo-sach-dau-an-1...
2,Shikimori Đâu Chỉ Dễ Thương - Tập 1 - Tặng Kèm...,33250.0,610,SÁCH TIẾNG VIỆT > MANGA - COMIC > MANGA > MANG...,Keigo Maki,Kim Đồng,Nhà Xuất Bản Kim Đồng,Bìa Mềm,144.0,https://www.fahasa.com/shikimori-dau-chi-de-th...
3,Boxset Sherlock Holmes Toàn Tập (Hộp 3 Tập) - ...,1090000.0,60,SÁCH TIẾNG VIỆT > VĂN HỌC > TRUYỆN TRINH THÁM ...,Sir Arthur Conan Doyle,Văn Học,Đông A,Bộ Hộp,1808.0,https://www.fahasa.com/boxset-sherlock-holmes-...
4,Combo Sách Giáo Trình New HSK 1 + Sổ Tay Học V...,325800.0,3000,SÁCH TIẾNG VIỆT > SÁCH HỌC NGOẠI NGỮ > TIẾNG HOA,Nhiều Tác Giả,Dân Trí,ZenBooks,Bìa Mềm,288.0,https://www.fahasa.com/combo-sach-giao-trinh-n...

### Kiểm tra missing và tách Category

In [ ]:
miss = df.isna().sum().to_frame("n_missing")
miss["pct"] = (miss["n_missing"] / len(df) * 100).round(1)
print(miss[miss["n_missing"] > 0])

df["Lvl1"] = df["Category"].str.split(" > ").str[0]
df["Lvl2"] = df["Category"].str.split(" > ").str[1]

       n_missing  pct
Price         25  2.7
Pages         75  8.1

### Xóa các dòng trùng

In [23]:
print("Số dòng trùng:", df.duplicated().sum())      
df = df.drop_duplicates().reset_index(drop=True)
print(df.shape)

Số dòng trùng: 91
(832, 12)

### Xóa giá trị không hợp lệ

In [24]:
bad_price = df["Price"] <= 0                     
bad_qty   = df["QuantitySold"] >= 999_999_999     
print(bad_price.sum(), bad_qty.sum())             

df = df[~(bad_price | bad_qty)].reset_index(drop=True)
print(df.shape)

87 63
(682, 12)

In [25]:
print((df["Price"] > 5_000_000).sum())           
df = df[df["Price"] <= 5_000_000].reset_index(drop=True)
print(df.shape)

59
(598, 12)

### Fill missing theo loại cột

In [26]:
is_book = df["Lvl1"].isin(["SÁCH TIẾNG VIỆT", "FOREIGN BOOKS"])

df["Price"] = df["Price"].fillna(df["Price"].median())

df["Pages_missing"] = df["Pages"].isna()         
med_pages = df.loc[is_book, "Pages"].median()
df.loc[is_book & df["Pages"].isna(), "Pages"] = med_pages

for c in ["Category", "Lvl1", "Lvl2", "Author", "Publisher"]:
    df[c] = df[c].fillna("Unknown")

df["Supplier"] = df["Supplier"].fillna(df["Supplier"].mode()[0])

df.loc[~is_book & df["CoverType"].isna(), "CoverType"] = "Không áp dụng"
df["CoverType"] = df["CoverType"].fillna(df.loc[is_book, "CoverType"].mode()[0])

print(df.isna().sum())

ProductName       0
Price             0
QuantitySold      0
Category          0
Author            0
Publisher         0
Supplier          0
CoverType         0
Pages            37
ProductURL        0
Lvl1              0
Lvl2              0
Pages_missing     0
dtype: int64

### Kiểm tra lại dữ liệu

In [27]:
assert (df["Price"] > 0).all()
assert (df["QuantitySold"] >= 0).all()
assert df[["Price", "QuantitySold", "Category", "CoverType"]].isna().sum().sum() == 0
print("Sạch:", df.shape)

Sạch: (598, 13)

### Lọc outliner bằng tứ phân vị

In [28]:
def iqr_fence(s, k=1.5):
    q1, q3 = s.quantile([0.25, 0.75])
    iqr = q3 - q1
    return q1 - k * iqr, q3 + k * iqr

for c in ["Price", "QuantitySold", "Pages"]:
    lo, hi = iqr_fence(df[c].dropna())
    n_out = ((df[c] < lo) | (df[c] > hi)).sum()
    print(c, "rào:", round(lo), round(hi), "| outlier:", n_out)
    df[c + "_clip"] = df[c].clip(lower=max(lo, df[c].min()), upper=hi)

Price rào: -138325 411875 | outlier: 59
QuantitySold rào: -9975 18425 | outlier: 59
Pages rào: -130 718 | outlier: 29

In [29]:
df["log_Price"] = np.log10(df["Price"])
df["log_Qty"]   = np.log10(df["QuantitySold"] + 1)

name = df["ProductName"].str.lower()
df["Is_set"]   = name.str.contains(r"boxset|combo|\(bộ |trọn bộ|hộp \d", regex=True)
df["Has_gift"] = name.str.contains("tặng kèm")
df["Campaign"] = df["ProductURL"].str.extract(r"fhs_campaign=(\w+)")[0]

df["Price_bin"] = pd.cut(df["Price"], [0, 50_000, 100_000, 200_000, 500_000, 5_000_000],
                         labels=["<50k", "50-100k", "100-200k", "200-500k", ">500k"])
df["Price_per_page"] = np.where(df["Pages"] > 0, df["Price"] / df["Pages"], np.nan)

top_q = df["QuantitySold"].quantile(0.75)
df["Bestseller"] = (df["QuantitySold"] >= top_q).astype(int)  

dummies = pd.get_dummies(df["CoverType"], prefix="Cover", dtype=int)
df = pd.concat([df, dummies], axis=1)

for c in ["log_Price", "log_Qty"]:                             
    df[c + "_z"] = (df[c] - df[c].mean()) / df[c].std()

In [ ]:
df.to_csv("fahasa_cleaned.csv", index=False, encoding="utf-8-sig")
print(df.shape)