# Stage 2:

### import thư viện:

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, mean_squared_error, r2_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

### Kết nối với database trong Mongodb Altas (dataset sạch)

In [3]:
import pandas as pd
from pymongo import MongoClient


uri = "mongodb://mrin9379_db_user:iOxgQWXsj7i30kSF@ac-8dydvgo-shard-00-00.b8wslzx.mongodb.net:27017,ac-8dydvgo-shard-00-01.b8wslzx.mongodb.net:27017,ac-8dydvgo-shard-00-02.b8wslzx.mongodb.net:27017/?ssl=true&replicaSet=atlas-fb5v22-shard-0&authSource=admin&appName=Cluster0"
client = MongoClient(uri)


db = client['Fahasa'] 
collection = db['Fahasa_cleaned']


print("Đang tải dữ liệu...")
cursor = collection.find({}) 


df = pd.DataFrame(list(cursor))


if '_id' in df.columns:
    df.drop(columns=['_id'], inplace=True)


print("Tải dữ liệu thành công!")
display(df.head())

Đang tải dữ liệu...
Tải dữ liệu thành công!

,ProductName,Price,QuantitySold,Category,Author,Publisher,Supplier,CoverType,Pages,ProductURL,...,Price_per_page,Bestseller,Cover_,Cover_Board Book,Cover_Bìa Cứng,Cover_Bìa Mềm,Cover_Bộ Hộp,Cover_Mixed Media Product,log_Price_z,log_Qty_z
0,Xứ Sở Miên Man - Phiên Bản Book Charm - Bìa Cứng,415000.0,1000,SÁCH TIẾNG VIỆT > VĂN HỌC > TIỂU THUYẾT,Jun Phạm,Phụ Nữ Việt Nam,Skybooks,Bìa Cứng,456.0,https://www.fahasa.com/xu-so-mien-man-phien-ba...,...,910.087719,0,0,0,1,0,0,0,1.322420,-0.422806
1,Boxset Bộ Sách Dấu Ấn 10 Năm Omega+ (Hộp 10 Cu...,4000000.0,48,SÁCH TIẾNG VIỆT > LỊCH SỬ - ĐỊA LÝ - TÔN... > ...,Nhiều Tác Giả,"Thế Giới, Tri Thức, Văn Học, Dân Trí",CÔNG TY CỔ PHẦN SÁCH OMEGA VIỆT NAM,Bộ Hộp,5280.0,https://www.fahasa.com/boxset-bo-sach-dau-an-1...,...,757.575758,0,0,0,0,0,1,0,3.728138,-2.029582
2,Shikimori Đâu Chỉ Dễ Thương - Tập 1 - Tặng Kèm...,33250.0,610,SÁCH TIẾNG VIỆT > MANGA - COMIC > MANGA > MANG...,Keigo Maki,Kim Đồng,Nhà Xuất Bản Kim Đồng,Bìa Mềm,144.0,https://www.fahasa.com/shikimori-dau-chi-de-th...,...,230.902778,0,0,0,0,1,0,0,-1.357714,-0.685721
3,Boxset Sherlock Holmes Toàn Tập (Hộp 3 Tập) - ...,1090000.0,60,SÁCH TIẾNG VIỆT > VĂN HỌC > TRUYỆN TRINH THÁM ...,Sir Arthur Conan Doyle,Văn Học,Đông A,Bộ Hộp,1808.0,https://www.fahasa.com/boxset-sherlock-holmes-...,...,602.876106,0,0,0,0,0,1,0,2.347719,-1.912917
4,Combo Sách Giáo Trình New HSK 1 + Sổ Tay Học V...,325800.0,3000,SÁCH TIẾNG VIỆT > SÁCH HỌC NGOẠI NGỮ > TIẾNG HOA,Nhiều Tác Giả,Dân Trí,ZenBooks,Bìa Mềm,288.0,https://www.fahasa.com/combo-sach-giao-trinh-n...,...,1131.250000,0,0,0,0,1,0,0,1.065478,0.161944

### Import dữ liệu thủ công(dùng để trình bày khi database bị lỗi kết nối)

In [ ]:
# df = pd.read_csv('../Data/fahasa_cleaned.csv')
# df

,ProductName,Price,QuantitySold,Category,Author,Publisher,Supplier,CoverType,Pages,ProductURL,...,Price_per_page,Bestseller,Cover_,Cover_Board Book,Cover_Bìa Cứng,Cover_Bìa Mềm,Cover_Bộ Hộp,Cover_Mixed Media Product,log_Price_z,log_Qty_z
0,Xứ Sở Miên Man - Phiên Bản Book Charm - Bìa Cứng,415000.0,1000,SÁCH TIẾNG VIỆT > VĂN HỌC > TIỂU THUYẾT,Jun Phạm,Phụ Nữ Việt Nam,Skybooks,Bìa Cứng,456.0,https://www.fahasa.com/xu-so-mien-man-phien-ba...,...,910.087719,0,0,0,1,0,0,0,1.322420,-0.422806
1,Boxset Bộ Sách Dấu Ấn 10 Năm Omega+ (Hộp 10 Cu...,4000000.0,48,SÁCH TIẾNG VIỆT > LỊCH SỬ - ĐỊA LÝ - TÔN... > ...,Nhiều Tác Giả,"Thế Giới, Tri Thức, Văn Học, Dân Trí",CÔNG TY CỔ PHẦN SÁCH OMEGA VIỆT NAM,Bộ Hộp,5280.0,https://www.fahasa.com/boxset-bo-sach-dau-an-1...,...,757.575758,0,0,0,0,0,1,0,3.728138,-2.029582
2,Shikimori Đâu Chỉ Dễ Thương - Tập 1 - Tặng Kèm...,33250.0,610,SÁCH TIẾNG VIỆT > MANGA - COMIC > MANGA > MANG...,Keigo Maki,Kim Đồng,Nhà Xuất Bản Kim Đồng,Bìa Mềm,144.0,https://www.fahasa.com/shikimori-dau-chi-de-th...,...,230.902778,0,0,0,0,1,0,0,-1.357714,-0.685721
3,Boxset Sherlock Holmes Toàn Tập (Hộp 3 Tập) - ...,1090000.0,60,SÁCH TIẾNG VIỆT > VĂN HỌC > TRUYỆN TRINH THÁM ...,Sir Arthur Conan Doyle,Văn Học,Đông A,Bộ Hộp,1808.0,https://www.fahasa.com/boxset-sherlock-holmes-...,...,602.876106,0,0,0,0,0,1,0,2.347719,-1.912917
4,Combo Sách Giáo Trình New HSK 1 + Sổ Tay Học V...,325800.0,3000,SÁCH TIẾNG VIỆT > SÁCH HỌC NGOẠI NGỮ > TIẾNG HOA,Nhiều Tác Giả,Dân Trí,ZenBooks,Bìa Mềm,288.0,https://www.fahasa.com/combo-sach-giao-trinh-n...,...,1131.250000,0,0,0,0,1,0,0,1.065478,0.161944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,Blue Period - Tập 5 - Tặng Kèm Bookmark Giấy +...,4600000.0,8400,SÁCH TIẾNG VIỆT > MANGA - COMIC > MANGA > MANG...,Yamaguchi Tsubasa,Trẻ,NXB Trẻ,Bìa Mềm,192.0,https://www.fahasa.com/blue-period-tap-5-tang-...,...,23958.333333,1,0,0,0,1,0,0,3.876533,0.710191
594,Dan Da Dan - Tập 1 - Tặng Kèm Special Cover,4275000.0,12700,SÁCH TIẾNG VIỆT > MANGA - COMIC > MANGA > MANG...,Yukinobu Tatsu,Kim Đồng,Nhà Xuất Bản Kim Đồng,Bìa Mềm,210.0,https://www.fahasa.com/dan-da-dan-tap-1-tang-k...,...,20357.142857,1,0,0,0,1,0,0,3.798735,0.930324
595,Cuộn Bao Sách Nylon TP 242 x 175 mm (10 Tờ/Cuộn),1800000.0,487100,VĂN PHÒNG PHẨM - DỤNG ... > DỤNG CỤ HỌC SINH >...,NaN,NaN,Công Ty TNHH Xuất Bản Phương Đông,NaN,NaN,https://www.fahasa.com/cuon-bao-sach-nylon-tp-...,...,NaN,1,1,0,0,0,0,0,2.880310,2.872552
596,Lên - Bản Mở Rộng #2 Cực Đỉnh Từ Party Game Lầy,4500000.0,11600,ĐỒ CHƠI > BOARD GAME > CARD GAMES,NaN,NaN,Boardgame Việt Nam,NaN,NaN,https://www.fahasa.com/len-ban-mo-rong-2-cuc-d...,...,NaN,1,1,0,0,0,0,0,3.853196,0.882078
597,Người Bà Tài Giỏi Vùng Saga - Tập 4 (Tái Bản 2...,4500000.0,240,SÁCH TIẾNG VIỆT > MANGA - COMIC > MANGA > MANG...,"Yoshichi Shimada, Saburo Ishikawa",Thế Giới,Skybooks,Bìa Mềm,213.0,https://www.fahasa.com/nguoi-ba-tai-gioi-vung-...,...,21126.760563,0,0,0,0,1,0,0,3.853196,-1.181185

## 1. Unsupervised Learning & Dimensionality Reduction (PCA)